input_data:
  dataset : ['ngsim']
  subject: 'vehicle'
  train_folder: 'train'
  val_folder: 'val'
  test_folder: 'test'
  observed_steps : 15
  prtediction_step : 25
  points_per_position : 2

training:
  save_model : True
  train : True
  validation_interval : 1
  save_folder : 'final_train_v4'
  learning_rate : 0.01
  milestones : [10,30,45]
  epoches : 80
  device : 'cuda:0'
  weight_decay : 0.0005
  model_dir : 'D:\cs637_pishgu_from_google_search\Pishgu\models\NGSIM'
  batch_size : 64

  


